dist: trusty
sudo: false
language: generic
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-4.5.1-Linux-x86_64.sh
    --output-document miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - conda config --set always_yes yes --set changeps1 no
  - conda info --all
install:
  - conda env create --quiet --file environment.yml
  - conda activate hetmech
  - pip install --editable .
  - conda list
script:
  - pytest hetmech
  - jupyter nbconvert --to=script --stdout *.ipynb |
    flake8 --exit-zero --show-source --ignore=E402,W291,E501,W391 -
  - flake8 --max-line-length=120 hetmech
